# Generated by Django 2.0.3 on 2018-11-22 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
