# Generated by Django 2.0.3 on 2018-05-10 02:53

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='img/account/', verbose_name=''),
        ),
    ]
