# Generated by Django 2.0.3 on 2018-05-10 04:53

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='img/account/', verbose_name='Image'),
        ),
    ]
