# Generated by Django 2.0.3 on 2018-05-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180510_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activate',
        ),
    ]
