# Generated by Django 2.0.3 on 2018-05-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180401_1048'),
        ('account', '0011_auto_20180510_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wanting_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
    ]
