# Generated by Django 2.0.3 on 2018-05-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_wanting_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wanting_product',
        ),
    ]
