# Generated by Django 2.0.3 on 2018-05-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180520_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='django_relative_url',
            new_name='relative_url',
        ),
    ]
