# Generated by Django 2.0.3 on 2018-05-22 17:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180522_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='account', verbose_name=''),
        ),
    ]
