# Generated by Django 2.0.3 on 2018-07-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20180523_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reciever',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
