# Generated by Django 2.0.3 on 2019-01-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20190102_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rules_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
