# Generated by Django 2.0.3 on 2018-06-01 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180526_2111'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.CharField(max_length=6),
        ),
    ]
