# Generated by Django 2.0.3 on 2018-06-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20180601_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
