# Generated by Django 2.0.3 on 2019-01-03 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlist', '0003_remove_watchlist_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=512)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watchlist.WatchList')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingOfferTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('matchingOffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching_offer.MatchingOffer')),
                ('talker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
