# Generated by Django 2.0.3 on 2019-01-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching_offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingoffer',
            name='watchlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watchlist.WatchList'),
        ),
    ]
