# Generated by Django 2.0.3 on 2019-01-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching_offer', '0002_auto_20190104_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingoffertalk',
            old_name='matchingOffer',
            new_name='matching_offer',
        ),
    ]
