# Generated by Django 2.0.3 on 2019-01-04 14:11

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matching_offer', '0003_auto_20190104_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='matching_offer', verbose_name='')),
                ('matching_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching_offer.MatchingOffer')),
            ],
        ),
        migrations.AlterField(
            model_name='matchingoffertalk',
            name='text',
            field=models.TextField(max_length=512, verbose_name=''),
        ),
    ]
