# Generated by Django 2.0.3 on 2018-06-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180526_2111'),
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportToBuyTodo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo_list.Todo')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            bases=('todo_list.todo',),
        ),
    ]
