# Generated by Django 2.0.3 on 2018-06-02 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0019_auto_20180602_1252'),
        ('todo_list', '0002_reporttobuytodo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportToBuyTodo',
            new_name='ReportToRecieveTodo',
        ),
    ]
