# Generated by Django 2.0.3 on 2018-06-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20180602_1311'),
        ('todo_list', '0003_auto_20180602_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTodo',
            fields=[
                ('todo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo_list.Todo')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            bases=('todo_list.todo',),
        ),
    ]
