# Generated by Django 2.0.3 on 2019-01-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_watched_count'),
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='product',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='products',
            field=models.ManyToManyField(related_name='watchlist_product', to='product.Product'),
        ),
    ]
