# Generated by Django 2.0.3 on 2019-01-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_auto_20190102_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='products',
        ),
    ]
