# Generated by Django 2.0.3 on 2018-08-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='お問い合わせ内容'),
        ),
    ]
