# Generated by Django 2.0.3 on 2018-03-28 16:49

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180328_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='products/images/', verbose_name='Image'),
        ),
    ]
