# Generated by Django 2.0.3 on 2018-03-28 17:27

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_optional_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ppoi3',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
