# Generated by Django 2.0.3 on 2018-03-29 10:34

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180328_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ppoi3',
        ),
        migrations.AddField(
            model_name='product',
            name='optional_image1',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='products/images/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='product',
            name='optional_image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='products/images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='products/images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='optional_image3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='products/images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='optional_image1',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='products/images/', verbose_name='optional_image1'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='optional_image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='products/images/', verbose_name='optional_image2'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='optional_image3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='products/images/', verbose_name='optional_image3'),
        ),
    ]
