# Generated by Django 2.0.3 on 2018-03-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180329_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image0',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='optional_image1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='optional_image2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='optional_image3',
            new_name='image3',
        ),
    ]
