# Generated by Django 2.0.3 on 2018-03-29 17:08

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20180329_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AlterField(
            model_name='product',
            name='image0',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='img/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='img/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='img/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='img/', verbose_name=''),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
