# Generated by Django 2.0.3 on 2018-04-01 10:48

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20180329_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image0',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='img/product/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='img/product/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='img/product/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='img/product/', verbose_name=''),
        ),
    ]
