# Generated by Django 2.0.3 on 2018-05-13 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_auto_20180401_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wanting_users',
            field=models.ManyToManyField(related_name='wanting_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
