# Generated by Django 2.0.3 on 2018-05-22 17:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_wanting_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image0',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='product', verbose_name=''),
        ),
    ]
