# Generated by Django 2.0.3 on 2018-07-24 04:22

from django.db import migrations, models
import hokudai_furima.product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20180602_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='access_level',
            field=models.CharField(choices=[('private', '非公開'), ('public', '公開')], default='公開', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, validators=[hokudai_furima.product.models.has_no_singlequote]),
        ),
    ]
