# Generated by Django 2.0.3 on 2018-11-02 11:48

from django.db import migrations, models
import hokudai_furima.product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20180724_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='access_level',
            field=models.CharField(choices=[('public', '公開'), ('private', '非公開')], default='public', max_length=10, verbose_name='公開/非公開'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='説明文'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='値段(円)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, validators=[hokudai_furima.product.models.has_no_singlequote], verbose_name='商品名'),
        ),
    ]
