# Generated by Django 2.0.3 on 2018-11-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_sold_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watched_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
