# Generated by Django 2.0.3 on 2019-01-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_remove_watchlist_products'),
        ('product', '0024_product_watched_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watchlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='watchlist.WatchList'),
        ),
    ]
