# Generated by Django 2.0.3 on 2019-01-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20190102_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watchlist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.WatchList'),
        ),
    ]
