# Generated by Django 2.1.5 on 2019-04-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
        ('product', '0029_auto_20190302_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lecture_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecture_category_products', to='lecture.LectureCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_category_products', to='product.Category'),
        ),
    ]
