# Generated by Django 2.0.3 on 2018-03-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='product',
        ),
        migrations.AddField(
            model_name='chat',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
