# Generated by Django 2.0.3 on 2018-03-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180319_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='talk',
        ),
        migrations.AddField(
            model_name='talk',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
    ]
