# Generated by Django 2.0.3 on 2018-05-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_wanting_users'),
        ('chat', '0005_auto_20180514_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='product_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
